version: '2'

services:
  sandiego.2020.codes:
    environment:
      - VIRTUAL_HOST=sandiego.2020.codes.local
      - LETSENCRYPT_HOST=sandiego.2020.codes.local
    build: .
    image: mountain/sandiego.2020.codes
    container_name: sandiego.2020.codes
    ports:
      # strapi runs on port 1337, so map this port out to port 7002 to access it.  the container always
      # specifies this it exposes this port in the Dockerfile.  to change this port (1337), change Dockerfile
      - 8855:8855
    networks:
      - mongonet
    restart: always

networks:
  mongonet:
    external: true

