version: '2'

services:
  sandiego.bipolars.for.elizabeth.infinito.blue:
    environment:
      - VIRTUAL_HOST=sandiego.bipolars.for.elizabeth.infinito.blue
      - LETSENCRYPT_HOST=sandiego.bipolars.for.elizabeth.infinito.blue
    build: .
    image: mountain/sandiego.bipolars.for.elizabeth.infinito.blue
    container_name: sandiego.bipolars.for.elizabeth.infinito.blue
    ports:
      # strapi runs on port 1337, so map this port out to port 7002 to access it.  the container always
      # specifies this it exposes this port in the Dockerfile.  to change this port (1337), change Dockerfile
      - 9003:9003
    networks:
      - mongonet
    restart: always

networks:
  mongonet:
    external: true

